#ifndef JSLANG_COMPILER_TOKEN_TOKEN_H
#define JSLANG_COMPILER_TOKEN_TOKEN_H

#include "compiler/source/source.h"

typedef enum {
    JSL_TOKEN_ILLEGAL,
    JSL_TOKEN_EOF,
    JSL_TOKEN_IDENTIFIER,
    JSL_TOKEN_INTEGER,
    JSL_TOKEN_FLOAT,
    JSL_TOKEN_STRING,
    JSL_TOKEN_FUNCTION,
    JSL_TOKEN_RETURN,
    JSL_TOKEN_CONST,
    JSL_TOKEN_LET,
    JSL_TOKEN_STRUCT,
    JSL_TOKEN_INTERFACE,
    JSL_TOKEN_IF,
    JSL_TOKEN_ELSE,
    JSL_TOKEN_WHILE,
    JSL_TOKEN_FOR,
    JSL_TOKEN_TRUE,
    JSL_TOKEN_FALSE,
    JSL_TOKEN_NULL,
    JSL_TOKEN_IMPORT,
    JSL_TOKEN_FROM,
    JSL_TOKEN_PLUS, JSL_TOKEN_MINUS, JSL_TOKEN_ASTERISK, JSL_TOKEN_SLASH, JSL_TOKEN_PERCENT,
    JSL_TOKEN_ASSIGN, JSL_TOKEN_EQUAL, JSL_TOKEN_NOT_EQUAL,
    JSL_TOKEN_LESS, JSL_TOKEN_GREATER, JSL_TOKEN_LESS_EQUAL, JSL_TOKEN_GREATER_EQUAL,
    JSL_TOKEN_AND, JSL_TOKEN_OR, JSL_TOKEN_BANG,
    JSL_TOKEN_LEFT_PAREN, JSL_TOKEN_RIGHT_PAREN, JSL_TOKEN_LEFT_BRACE, JSL_TOKEN_RIGHT_BRACE,
    JSL_TOKEN_LEFT_BRACKET, JSL_TOKEN_RIGHT_BRACKET, JSL_TOKEN_SEMICOLON, JSL_TOKEN_QUESTION, JSL_TOKEN_COLON,
    JSL_TOKEN_COMMA, JSL_TOKEN_DOT
} JslTokenType;

typedef struct {
    JslTokenType type;
    const char *start;
    size_t length;
    JslPosition position;
} JslToken;

const char *jsl_token_type_name(JslTokenType type);
JslTokenType jsl_keyword_type(const char *start, size_t length);

#endif
